service: petrealm

custom:
  dotenv:
    path: .env

package:
  individually: true
  include:
    - backend/**
  exclude:
    - node_modules/**
    - .env
    - .git/**
    - README.md

functions:
  hungerDecay:
    handler: backend/src/services/hunger-decay.handler
    timeout: 30
    events:
      - schedule:
          rate: rate(1 hour)

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  environment:
    DB_HOST: pets.c1asi2ku8ijs.us-east-2.rds.amazonaws.com
    DB_PORT: 5432
    DB_DATABASE: pets
    DB_USER: petslogin
    DB_PASSWORD: cYo4oGdBnbQJQqAFC5kN
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:DescribeLogStreams"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "arn:aws:logs:us-east-2:*:*"
